### ISSUE TITLE
Build issues on Debian?

### ISSUE THREAD

**Issue by awalton** [PipeWire/pipewire#6] opened 2017-07-30 15:52 UTC
Was listening to your talk and I'm interested in problems in this space so I decided to give it a build and look around the code. Seemed to have a number of build issues on my system:

Didn't want to build on my system without SDL2 despite it not being a "requirement". I don't know Meson yet so I don't know how to correct this problem other than just installing libsdl2 development package (path of lease resistance).

Had to tack in this short patch to get it to build completely as it errored out with a bunch of what I am guessing is eglibc-incompatiblity junk given the quickest google I did.

FAILED: src/gst/gstpipewire@sha/gstpipewire.c.o 
cc  '-Isrc/gst/gstpipewire@sha' '-fdiagnostics-color=always' '-Isrc/gst' '-I../src/gst' '-I.' '-I../.' '-Ispa/include' '-I../spa/include' '-Isrc' '-I../src' '-pipe' '-Wall' '-Winvalid-pch' '-std=gnu99' '-DHAVE_CONFIG_H' '-O2' '-g' '-fPIC' '-I/usr/include/glib-2.0' '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' '-pthread' '-I/usr/include/gio-unix-2.0/' '-pthread' '-I/usr/include/gstreamer-1.0' '-pthread' '-MMD' '-MQ' 'src/gst/gstpipewire@sha/gstpipewire.c.o' '-MF' 'src/gst/gstpipewire@sha/gstpipewire.c.o.d' -o 'src/gst/gstpipewire@sha/gstpipewire.c.o' -c ../src/gst/gstpipewire.c
In file included from ../spa/include/spa/graph.h:27:0,
                 from ../spa/include/spa/graph-scheduler3.h:27,
                 from ../src/pipewire/core.h:28,
                 from ../src/pipewire/client.h:33,
                 from ../src/pipewire/pipewire.h:29,
                 from ../src/gst/gstpipewiresrc.h:26,
                 from ../src/gst/gstpipewire.c:35:
/usr/include/stdio.h:316:6: error: unknown type name ‘_IO_cookie_io_functions_t’
      _IO_cookie_io_functions_t __io_funcs) __THROW __wur;

Went away with:

diff --git a/spa/include/spa/graph.h b/spa/include/spa/graph.h
index 6408586..1d46cbe 100644
--- a/spa/include/spa/graph.h
+++ b/spa/include/spa/graph.h
@@ -20,6 +20,10 @@
 #ifndef __SPA_GRAPH_H__
 #define __SPA_GRAPH_H__
 
+#ifndef _GNU_SOURCE
+#define _GNU_SOURCE
+#endif
+
 #ifdef __cplusplus
 extern "C" {
 #endif

(There's probably a better patch though.)

Seems like this could be pretty interesting!

**Comment by philn** [comment] 2017-09-19 13:56
I haven't reached that step yet because:
```
make
ninja-build -C build
make: ninja-build: Command not found
```
On Debian ninja is called ninja, not ninja-build ;)

**Comment by wtay** [comment] 2017-09-19 14:12
I use ninja instead of ninja-build now, it seems to work fine on fedora too these days.

**Comment by philn** [comment] 2017-09-19 14:16
Builds fine on Debian Testing here as well now.

**Comment by harryhaaren** [comment] 2017-09-28 16:46
+1, have this issue too - patch above didn't fix it directly... added the same #ifdefs to `pod-graph.h` which seems to have fixed it. The root cause is that on some systems that define isn't enabled, and depending on the #include order, we'll have to add that #ifdef .. there's a better method to fix than hacking into the file that's failing, but for now I'll move on.

That led me to another compile issue, see https://github.com/PipeWire/pipewire/issues/22

**Comment by wtay** [comment] 2017-09-29 11:39
should be fixed in git now

**Closed by wtay** 2017-09-29 11:39 UTC

**Comment by awalton** [comment] 2017-09-29 21:09
Thanks for the follow up Wim and everyone.
